import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import Database from 'better-sqlite3';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
fs.mkdirSync(path.join(root, '..', 'database'), { recursive: true });
const db = new Database(path.join(root, '..', 'database', 'nagerx.db'));
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS Users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password TEXT NOT NULL, role TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS Incidents (id INTEGER PRIMARY KEY AUTOINCREMENT, incident_code TEXT UNIQUE NOT NULL, type TEXT NOT NULL, location TEXT NOT NULL, latitude REAL, longitude REAL, description TEXT, severity TEXT NOT NULL, status TEXT DEFAULT 'Reported', reported_by INTEGER, created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS TrafficData (id INTEGER PRIMARY KEY AUTOINCREMENT, location TEXT NOT NULL, latitude REAL, longitude REAL, congestion_level TEXT NOT NULL, average_speed REAL, recorded_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS Routes (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, start_location TEXT, destination TEXT, distance REAL, estimated_time REAL, fuel_estimate REAL, efficiency TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS Notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, title TEXT, message TEXT, type TEXT, is_read INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS Locations (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, city TEXT NOT NULL, latitude REAL NOT NULL, longitude REAL NOT NULL, type TEXT DEFAULT 'Area');`);

const seed = () => {
  const user = db.prepare('INSERT OR IGNORE INTO Users (name,email,password,role) VALUES (?,?,?,?)');
  [['Aarav Citizen','citizen@nagerx.demo','citizen123','Citizen'],['Priya Authority','authority@nagerx.demo','authority123','Authority'],['Rohan Logistics','logistics@nagerx.demo','logistics123','Logistics']].forEach(([name,email,password,role]) => user.run(name,email,bcrypt.hashSync(password,10),role));
  const authority = db.prepare('SELECT id FROM Users WHERE email = ?').get('authority@nagerx.demo').id;
  const citizen = db.prepare('SELECT id FROM Users WHERE email = ?').get('citizen@nagerx.demo').id;
  const incidents = [['Road blockage','Pari Chowk','Construction debris near underpass','High',28.4652,77.5088,'In Progress'],['Accident','Knowledge Park II','Two-car collision, emergency lane open','Critical',28.4742,77.4831,'Investigating'],['Waterlogging','Surajpur Road','Water collecting after heavy rain','Medium',28.4931,77.5112,'Reported'],['Construction','Gaur City','Lane closure with active work crew','Low',28.6044,77.4378,'Resolved'],['Traffic signal','Alpha 1','Signal outage causing delays','High',28.4685,77.5057,'Reported'],['Road blockage','Sector 18','Delivery vehicle blocking service road','Medium',28.5708,77.3219,'Resolved'],['Accident','Yamuna Expressway','Minor collision, shoulder occupied','High',28.4142,77.555,'Reported'],['Waterlogging','Kasna','Flooded junction, use alternate route','Critical',28.4312,77.5171,'In Progress'],['Construction','Techzone 4','Metro utility work in progress','Low',28.5891,77.4053,'Investigating'],['Traffic signal','Botanical Garden','Signal timing issue at crossing','Medium',28.5642,77.334,'Resolved']];
  const addIncident = db.prepare('INSERT OR IGNORE INTO Incidents (incident_code,type,location,description,severity,latitude,longitude,status,reported_by) VALUES (?,?,?,?,?,?,?,?,?)');
  incidents.forEach((item,index) => addIncident.run(`NX-${1001+index}`,item[0],item[1],item[2],item[3],item[4],item[5],item[6],index%2 ? citizen : authority));
  const traffic = [['Pari Chowk',28.4652,77.5088,'High',18],['Knowledge Park',28.4742,77.4831,'Critical',11],['Surajpur',28.4931,77.5112,'Medium',28],['Gaur City',28.6044,77.4378,'Low',42],['Alpha 1',28.4685,77.5057,'High',21],['Kasna',28.4312,77.5171,'Critical',9],['Sector 18',28.5708,77.3219,'Medium',31],['Techzone',28.5891,77.4053,'Low',45],['Yamuna Expressway',28.4142,77.555,'High',24],['Botanical Garden',28.5642,77.334,'Medium',30]];
  if (!db.prepare('SELECT COUNT(*) count FROM TrafficData').get().count) { const addTraffic = db.prepare('INSERT INTO TrafficData (location,latitude,longitude,congestion_level,average_speed) VALUES (?,?,?,?,?)'); traffic.forEach(row => addTraffic.run(...row)); }
  if (!db.prepare('SELECT COUNT(*) count FROM Routes').get().count) { const addRoute = db.prepare('INSERT INTO Routes (user_id,start_location,destination,distance,estimated_time,fuel_estimate,efficiency) VALUES (?,?,?,?,?,?,?)'); [['Pari Chowk','Noida Sector 62',18.4,38,1.7,'Efficient'],['Gaur City','IGI Airport',48.2,82,4.4,'Moderate'],['Alpha 1','Jewar Airport',52.1,65,4.8,'Efficient'],['Kasna','Greater Noida West',16.8,35,1.6,'Moderate'],['Techzone','Sector 18',24.6,49,2.2,'Efficient']].forEach(row => addRoute.run(citizen,...row)); }
  db.prepare('INSERT INTO Notifications (user_id,title,message,type) VALUES (?,?,?,?)').run(citizen,'Critical alert nearby','High congestion reported near Knowledge Park II.','alert');
}; seed();

const areaDirectory = [
  ['Dwarka Sector 21','Delhi',28.5521,77.0580],['Dwarka Sector 8','Delhi',28.5650,77.0670],['Dwarka Sector 9','Delhi',28.5745,77.0650],['Dwarka Sector 10','Delhi',28.5810,77.0580],['Dwarka Sector 11','Delhi',28.5865,77.0520],['Dwarka Sector 12','Delhi',28.5920,77.0560],['Dwarka Sector 13','Delhi',28.5970,77.0630],['Dwarka Sector 14','Delhi',28.6020,77.0700],['Dwarka Mor','Delhi',28.6195,77.0330],['Nawada','Delhi',28.6200,77.0450],['Uttam Nagar West','Delhi',28.6210,77.0560],['Uttam Nagar East','Delhi',28.6240,77.0650],['Janakpuri West','Delhi',28.6295,77.0770],['Janakpuri East','Delhi',28.6290,77.0810],['Tilak Nagar','Delhi',28.6360,77.0960],['Subhash Nagar','Delhi',28.6400,77.1060],['Tagore Garden','Delhi',28.6430,77.1120],['Rajouri Garden Blue Line','Delhi',28.6490,77.1220],['Ramesh Nagar','Delhi',28.6500,77.1310],['Moti Nagar','Delhi',28.6580,77.1420],['Kirti Nagar','Delhi',28.6560,77.1500],['Shadipur','Delhi',28.6510,77.1580],['Patel Nagar','Delhi',28.6460,77.1690],['Rajendra Place','Delhi',28.6420,77.1780],['Karol Bagh Blue Line','Delhi',28.6440,77.1890],['Jhandewalan','Delhi',28.6445,77.1990],['R K Ashram Marg','Delhi',28.6390,77.2080],['Rajiv Chowk Blue Line','Delhi',28.6328,77.2195],['Barakhamba Road','Delhi',28.6305,77.2250],['Mandi House Blue Line','Delhi',28.6255,77.2340],['Supreme Court Metro','Delhi',28.6220,77.2410],['Indraprastha Metro','Delhi',28.6200,77.2500],['Yamuna Bank','Delhi',28.6233,77.2670],['Laxmi Nagar Blue Line','Delhi',28.6300,77.2770],['Nirman Vihar','Delhi',28.6360,77.2860],['Preet Vihar Blue Line','Delhi',28.6415,77.2955],['Karkarduma','Delhi',28.6500,77.3060],['Anand Vihar Blue Line','Delhi',28.6469,77.3150],['Kaushambi','Ghaziabad',28.6450,77.3260],['Vaishali','Ghaziabad',28.6490,77.3390],['IP Extension','Delhi',28.6280,77.3010],['Vinod Nagar East','Delhi',28.6200,77.3040],['New Ashok Nagar','Delhi',28.5890,77.3020],['Noida Sector 15','Noida',28.5865,77.3110],['Noida Sector 16','Noida',28.5780,77.3170],['Noida Sector 18 Blue Line','Noida',28.5708,77.3219],['Botanical Garden Blue Line','Noida',28.5630,77.3340],['Golf Course Noida','Noida',28.5570,77.3450],['Noida City Centre','Noida',28.5740,77.3560],['Noida Sector 34','Noida',28.5780,77.3620],['Noida Sector 52 Blue Line','Noida',28.5850,77.3690],['Noida Sector 61','Noida',28.5940,77.3730],['Noida Sector 59','Noida',28.6060,77.3730],['Noida Sector 62 Blue Line','Noida',28.6270,77.3740],['Noida Electronic City','Noida',28.6280,77.3910],
  ['Pari Chowk','Greater Noida',28.4652,77.5088],['Alpha 1','Greater Noida',28.4685,77.5057],['Alpha 2','Greater Noida',28.4746,77.4964],['Beta 1','Greater Noida',28.4764,77.5021],['Beta 2','Greater Noida',28.4821,77.4992],['Gamma 1','Greater Noida',28.4628,77.4934],['Delta 1','Greater Noida',28.4551,77.5008],['Knowledge Park I','Greater Noida',28.4762,77.4921],['Knowledge Park II','Greater Noida',28.4742,77.4831],['Knowledge Park III','Greater Noida',28.4816,77.4757],['Surajpur','Greater Noida',28.4931,77.5112],['Kasna','Greater Noida',28.4312,77.5171],['Gaur City','Greater Noida',28.6044,77.4378],['Techzone 4','Greater Noida',28.5891,77.4053],['Noida Extension','Greater Noida',28.6078,77.4357],['Yamuna Expressway','Greater Noida',28.4142,77.5550],['Jewar','Greater Noida',28.1270,77.5573],['Dadri','Greater Noida',28.5526,77.5540],['Ecotech','Greater Noida',28.4940,77.5350],['Sector 18','Noida',28.5708,77.3219],
  ['Connaught Place','Delhi',28.6315,77.2167],['India Gate','Delhi',28.6129,77.2295],['Karol Bagh','Delhi',28.6514,77.1907],['Rajouri Garden','Delhi',28.6422,77.1225],['Dwarka','Delhi',28.5921,77.0460],['Janakpuri','Delhi',28.6219,77.0878],['Rohini','Delhi',28.7495,77.0565],['Pitampura','Delhi',28.7033,77.1322],['Model Town','Delhi',28.7177,77.1910],['Civil Lines','Delhi',28.6762,77.2250],['Kashmere Gate','Delhi',28.6675,77.2281],['Chandni Chowk','Delhi',28.6506,77.2303],['Lajpat Nagar','Delhi',28.5677,77.2433],['Saket','Delhi',28.5244,77.2066],['Hauz Khas','Delhi',28.5494,77.2001],['Vasant Kunj','Delhi',28.5421,77.1472],['Mehrauli','Delhi',28.5245,77.1855],['Greater Kailash','Delhi',28.5417,77.2382],['New Friends Colony','Delhi',28.5677,77.2636],['Mayur Vihar','Delhi',28.6083,77.2947],['Preet Vihar','Delhi',28.6415,77.2955],['Shahdara','Delhi',28.6735,77.2890],['Anand Vihar','Delhi',28.6469,77.3150],['Okhla','Delhi',28.5355,77.2732],['Vasant Vihar','Delhi',28.5607,77.1608],['IGI Airport','Delhi',28.5562,77.1000]
];
const addArea = db.prepare('INSERT OR IGNORE INTO Locations (name,city,latitude,longitude) VALUES (?,?,?,?)');
areaDirectory.forEach(area => addArea.run(...area));

const app = express();
const allowedOrigins = new Set([
  ...((process.env.CLIENT_URL || '').split(',').map(origin => origin.trim()).filter(Boolean)),
  'http://localhost:5173',
  'http://127.0.0.1:5173',
  'http://localhost:5174',
  'http://127.0.0.1:5174'
]);
const isAllowedOrigin = origin => !origin || allowedOrigins.has(origin) || /^https:\/\/[-a-z0-9]+(?:-[a-z0-9]+)*-\d+\.app\.github\.dev$/i.test(origin) || /^https:\/\/[-a-z0-9]+\.github\.dev$/i.test(origin);
app.use(cors({ origin: (origin, callback) => isAllowedOrigin(origin) ? callback(null, true) : callback(null, false) }));
app.use(express.json());
const tokenFor = user => jwt.sign(user,process.env.JWT_SECRET||'local-secret',{expiresIn:'7d'});
const auth = (req,res,next) => { try { req.user=jwt.verify(req.headers.authorization?.split(' ')[1],process.env.JWT_SECRET||'local-secret'); next(); } catch { res.status(401).json({error:'Authentication required'}); } };
const roles = (...allowed) => (req,res,next) => allowed.includes(req.user.role) ? next() : res.status(403).json({error:'Insufficient permissions'});
const demoPredictions = { mode:'Pilot Simulation', current:{label:'Moderate',score:58}, windows:[{label:'Next 30 min',pressure:'High',score:76},{label:'Next 1 hour',pressure:'High',score:82},{label:'Next 2 hours',pressure:'Moderate',score:64}], hotspots:[{name:'Knowledge Park II',current:'High',predicted:'Critical',time:'18 min',action:'Divert through Alpha 1'},{name:'Pari Chowk',current:'Moderate',predicted:'High',time:'32 min',action:'Meter incoming traffic'},{name:'Kasna Junction',current:'Critical',predicted:'High',time:'Now',action:'Keep alternate corridor open'}] };
const demoTransit = [{mode:'Bus',route:'101',next:'Pari Chowk',eta:6,crowding:'Moderate',status:'On schedule'},{mode:'Bus',route:'203',next:'Knowledge Park II',eta:11,crowding:'Low',status:'On schedule'},{mode:'Metro',route:'Blue Line',next:'Noida Sector 18',eta:4,crowding:'High',status:'Minor delay'},{mode:'Metro',route:'Aqua Line',next:'Alpha 1',eta:8,crowding:'Moderate',status:'On schedule'}];
const demoDeliveries = [['NX-D01','Gaur City','High',8.4],['NX-D02','Techzone 4','Medium',12.1],['NX-D03','Sector 18','High',15.8],['NX-D04','Pari Chowk','Low',5.2],['NX-D05','Knowledge Park II','Critical',9.7],['NX-D06','Alpha 1','Medium',6.6],['NX-D07','Kasna','High',10.4],['NX-D08','Gaur City','Low',7.1],['NX-D09','Techzone 4','Medium',13.2],['NX-D10','Pari Chowk','Low',4.8],['NX-D11','Sector 18','High',17.5],['NX-D12','Alpha 1','Medium',7.8]].map(([id,location,priority,distance])=>({id,location,priority,distance}));
app.get('/api/health',(_,res)=>res.json({status:'ok',message:'NagarX API is running'}));
app.get('/api/predictions',auth,(_,res)=>res.json(demoPredictions));
app.get('/api/transit',auth,(_,res)=>res.json({mode:'Demo Simulation',items:demoTransit}));
app.get('/api/deliveries',auth,(_,res)=>res.json({mode:'Illustrative Result',orders:demoDeliveries}));
app.post('/api/deliveries/cluster',auth,(_,res)=>{const groups=demoDeliveries.reduce((acc,order)=>{const key=order.location.replace(/\s+(II|1|4)$/i,'');(acc[key] ||= []).push(order);return acc;},{});res.json({mode:'Illustrative Result',before_trips:8,after_trips:Object.keys(groups).length,groups:Object.entries(groups).map(([location,orders])=>({location,orders}))});});
app.post('/api/emergency/route',auth,(req,res)=>{const emergencyType=['Ambulance','Fire','Police'].includes(req.body?.type)?req.body.type:'Ambulance';res.json({mode:'Local Simulation',type:emergencyType,corridor:'Knowledge Park II - Pari Chowk - Kailash Hospital',junctions:['Knowledge Park II','Alpha 1','Pari Chowk','Hospital'],estimated_response_minutes:14,diversion:'Use Surajpur Road for regular traffic'});});
app.get('/api/alerts',auth,(req,res)=>res.json([{id:'AI-01',type:'AI Prediction',severity:'High',title:'Pressure forecast',location:'Knowledge Park II',message:'Critical pressure predicted within 18 minutes.',created_at:new Date().toISOString()},{id:'TR-02',type:'Traffic',severity:'High',title:'Speed drop detected',location:'Pari Chowk',message:'Average speed is below the pilot threshold.',created_at:new Date(Date.now()-480000).toISOString()},{id:'LG-03',type:'Logistics',severity:'Medium',title:'Delivery load cluster',location:'Gaur City',message:'Demand is concentrated in two nearby zones.',created_at:new Date(Date.now()-840000).toISOString()},...db.prepare('SELECT id,title,message,type,created_at FROM Notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 8').all(req.user.id)]));
app.get('/api/locations',auth,async(req,res)=>{const query=(req.query.query||'').trim().toLowerCase();let locations=query?db.prepare("SELECT * FROM Locations WHERE lower(name) LIKE ? OR lower(city) LIKE ? ORDER BY name LIMIT 12").all(`%${query}%`,`%${query}%`):db.prepare('SELECT * FROM Locations ORDER BY city,name LIMIT 12').all();if(locations.length||!query)return res.json(locations);try{const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=8&countrycodes=in&q=${encodeURIComponent(`${query}, Delhi NCR, India`)}`,{headers:{'User-Agent':'NagarX-local-city-hub/1.0'},signal:AbortSignal.timeout(3500)});const remote=await response.json();const addRemote=db.prepare('INSERT OR IGNORE INTO Locations (name,city,latitude,longitude,type) VALUES (?,?,?,?,?)');remote.filter(item=>item.lat&&item.lon).forEach(item=>{const name=item.name||item.display_name.split(',')[0];const city=/noida|greater noida/i.test(item.display_name)?'Greater Noida':'Delhi';addRemote.run(name,city,Number(item.lat),Number(item.lon),'OSM area');});locations=db.prepare("SELECT * FROM Locations WHERE lower(name) LIKE ? OR lower(city) LIKE ? ORDER BY name LIMIT 12").all(`%${query}%`,`%${query}%`);res.json(locations);}catch{res.json([]);}});
app.post('/api/auth/register',(req,res)=>{const {name,email,password,role='Citizen'}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Name, email and password are required'});try{const result=db.prepare('INSERT INTO Users (name,email,password,role) VALUES (?,?,?,?)').run(name,email.toLowerCase(),bcrypt.hashSync(password,10),['Citizen','Authority','Logistics'].includes(role)?role:'Citizen');const user=db.prepare('SELECT id,name,email,role FROM Users WHERE id=?').get(result.lastInsertRowid);res.status(201).json({user,token:tokenFor(user)});}catch{res.status(409).json({error:'Email already registered'});}});
app.post('/api/auth/login',(req,res)=>{const user=db.prepare('SELECT * FROM Users WHERE email=?').get(req.body.email?.toLowerCase());if(!user||!bcrypt.compareSync(req.body.password||'',user.password))return res.status(401).json({error:'Invalid email or password'});const safe={id:user.id,name:user.name,email:user.email,role:user.role};res.json({user:safe,token:tokenFor(safe)});});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:db.prepare('SELECT id,name,email,role FROM Users WHERE id=?').get(req.user.id)}));
app.put('/api/auth/me',auth,(req,res)=>{const name=String(req.body.name||'').trim();if(name.length<2||name.length>80)return res.status(400).json({error:'Name must be between 2 and 80 characters'});db.prepare('UPDATE Users SET name=? WHERE id=?').run(name,req.user.id);const user=db.prepare('SELECT id,name,email,role FROM Users WHERE id=?').get(req.user.id);res.json({user,token:tokenFor(user)});});
app.get('/api/incidents',auth,(_,res)=>res.json(db.prepare('SELECT i.*,u.name reporter_name FROM Incidents i LEFT JOIN Users u ON u.id=i.reported_by ORDER BY i.created_at DESC').all()));
app.get('/api/incidents/:id',auth,(req,res)=>{const item=db.prepare('SELECT * FROM Incidents WHERE id=?').get(req.params.id);item?res.json(item):res.status(404).json({error:'Incident not found'});});
app.post('/api/incidents',auth,(req,res)=>{const {type,location,description,severity,latitude,longitude}=req.body;if(!type||!location||!description||!severity)return res.status(400).json({error:'Type, location, description and severity are required'});const last=db.prepare('SELECT incident_code FROM Incidents ORDER BY id DESC LIMIT 1').get()?.incident_code?.match(/\d+/)?.[0]||1000;const result=db.prepare('INSERT INTO Incidents (incident_code,type,location,latitude,longitude,description,severity,reported_by) VALUES (?,?,?,?,?,?,?,?)').run(`NX-${Number(last)+1}`,type,location,Number(latitude)||28.4742,Number(longitude)||77.4831,description,severity,req.user.id);const incident=db.prepare('SELECT * FROM Incidents WHERE id=?').get(result.lastInsertRowid);const notify=db.prepare('INSERT INTO Notifications (user_id,title,message,type) VALUES (?,?,?,?)');db.prepare("SELECT id FROM Users WHERE role='Authority'").all().forEach(authority=>notify.run(authority.id,'New incident reported',`${incident.incident_code}: ${incident.type} at ${incident.location} needs response.`,'incident'));res.status(201).json(incident);});
app.put('/api/incidents/:id',auth,roles('Authority'),(req,res)=>{const {status,severity}=req.body;const existing=db.prepare('SELECT * FROM Incidents WHERE id=?').get(req.params.id);db.prepare("UPDATE Incidents SET status=COALESCE(?,status),severity=COALESCE(?,severity),updated_at=CURRENT_TIMESTAMP WHERE id=?").run(status,severity,req.params.id);const updated=db.prepare('SELECT * FROM Incidents WHERE id=?').get(req.params.id);if(existing?.reported_by&&status==='Resolved')db.prepare('INSERT INTO Notifications (user_id,title,message,type) VALUES (?,?,?,?)').run(existing.reported_by,'Incident resolved',`${updated.incident_code} at ${updated.location} has been marked resolved.`,'resolved');res.json(updated);});
app.delete('/api/incidents/:id',auth,roles('Authority'),(req,res)=>{db.prepare('DELETE FROM Incidents WHERE id=?').run(req.params.id);res.status(204).end();});
app.get('/api/traffic',auth,(_,res)=>res.json(db.prepare('SELECT * FROM TrafficData ORDER BY recorded_at DESC').all()));
app.get('/api/routes',auth,(req,res)=>res.json(db.prepare("SELECT * FROM Routes WHERE user_id=? OR ? IN ('Authority','Logistics') ORDER BY created_at DESC").all(req.user.id,req.user.role)));
app.post('/api/routes',auth,(req,res)=>{const {start_location,destination}=req.body;if(!start_location||!destination)return res.status(400).json({error:'Start and destination are required'});const seed=`${start_location}|${destination}`.split('').reduce((sum,char)=>sum+char.charCodeAt(0),0);const distance=Math.round((12+(seed%29))*10)/10;const route={start_location,destination,distance,estimated_time:Math.round(distance*1.8),fuel_estimate:Math.round(distance*.09*10)/10,efficiency:'DEMO - efficient'};const result=db.prepare('INSERT INTO Routes (user_id,start_location,destination,distance,estimated_time,fuel_estimate,efficiency) VALUES (?,?,?,?,?,?,?)').run(req.user.id,...Object.values(route));res.status(201).json({...route,id:result.lastInsertRowid,alternative:{...route,distance:route.distance+3.2,estimated_time:route.estimated_time+8}});});
app.get('/api/notifications',auth,(req,res)=>res.json(db.prepare('SELECT * FROM Notifications WHERE user_id=? OR user_id IS NULL ORDER BY created_at DESC').all(req.user.id)));
app.get('/api/analytics',auth,(_,res)=>{const incidents=db.prepare('SELECT type,severity,status,COUNT(*) count FROM Incidents GROUP BY type,severity,status').all();const totals=db.prepare("SELECT COUNT(*) total,SUM(status!='Resolved') open,SUM(status='Resolved') resolved FROM Incidents").get();const routes=db.prepare("SELECT AVG(efficiency='Efficient') efficiency,SUM(fuel_estimate) fuel FROM Routes").get();res.json({totals,incidents,routes,active_alerts:db.prepare("SELECT COUNT(*) count FROM Incidents WHERE severity IN ('High','Critical') AND status!='Resolved'").get().count,average_response_minutes:26});});
const clientDist = path.join(root, '..', 'client', 'dist');
if (fs.existsSync(clientDist)) {
  app.use(express.static(clientDist));
  app.get('*', (req, res, next) => req.path.startsWith('/api/') ? next() : res.sendFile(path.join(clientDist, 'index.html')));
}
app.listen(process.env.PORT||5000, '127.0.0.1', ()=>console.log(`NagarX API running on http://localhost:${process.env.PORT||5000}`));